# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-21 17:17
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations
import popolo.behaviors.models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=b'', populate_from=b'id'),
        ),
    ]
