# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-21 17:18
from __future__ import unicode_literals

from django.db import migrations

def copy_id_into_slug(apps, schema_editor):
    Area = apps.get_model('popolo', 'Area')
    for area in Area.objects.all():
        area.slug = area.id
        area.save()


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0002_auto_20170921_1717'),
    ]

    operations = [
        migrations.RunPython(copy_id_into_slug),
    ]
