# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 13:53
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import popolo.behaviors.models


def copy_id_into_slug(apps, schema_editor):
    Person = apps.get_model('popolo', 'Person')
    for person in Person.objects.all():
        person.slug = person.id
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0003_auto_20170921_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.CharField(max_length=512, null=True, verbose_name='slug'),
        ),
        migrations.RunPython(copy_id_into_slug),
    ]
