# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 13:58
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations
import popolo.behaviors.models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0004_auto_20180315_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='area',
            name='object_id',
        ),
    ]
